export const STORAGE_TERMS_KEY = 'lido-terms-agree'
export const STORAGE_KEY_CONNECTOR = 'lido-connector'
export const STORAGE_KEY_SAVED_SETTINGS = 'lido-dao-voting-ui-settings'
export const STORAGE_THEME_AUTO_KEY = 'lido-theme-auto'
export const STORAGE_THEME_MANUAL_KEY = 'lido-theme-manual'
